const actionTypes =  {
  LOGIN_FAILURE: Symbol('LOGIN_FAILURE'),
  LOGIN_STATUS: Symbol('LOGIN_STATUS'),
  AUTHENTICTION_ROLE_SUCCESS:Symbol('AUTHENTICTION_ROLE_SUCCESS'),
  GET_DEFAULT_SHEET_LIST_SUCCESS: Symbol('GET_DEFAULT_SHEET_LIST_SUCCESS'),
  GET_DEFAULT_SHEET_LIST_FAILURE: Symbol('GET_DEFAULT_SHEET_LIST_FAILURE'),
  GET_LAST_DAYS_SHEET_LIST_SUCCESS: Symbol('GET_LAST_DAYS_SHEET_LIST_SUCCESS'),
  GET_LAST_DAYS_SHEET_LIST_FAILURE: Symbol('GET_LAST_DAYS_SHEET_LIST_FAILURE'),
  GET_LAST_WEEK_SHEET_LIST_SUCCESS: Symbol('GET_LAST_WEEK_SHEET_LIST_SUCCESS'),
  GET_LAST_WEEK_SHEET_LIST_FAILURE: Symbol('GET_LAST_WEEK_SHEET_LIST_FAILURE'),
  GET_HALF_YEAR_SHEET_LIST_SUCCESS: Symbol('GET_HALF_YEAR_SHEET_LIST_SUCCESS'),
  GET_HALF_YEAR_SHEET_LIST_FAILURE: Symbol('GET_HALF_YEAR_SHEET_LIST_FAILURE'),
  GET_UNREPORTED_SHEET_LIST_SUCCESS: Symbol('GET_UNREPORTED_SHEET_LIST_SUCCESS'),
  GET_UNREPORTED_SHEET_LIST_FAILURE: Symbol('GET_UNREPORTED_SHEET_LIST_FAILURE'),
  GET_CHECKING_SHEET_LIST_SUCCESS: Symbol('GET_CHECKING_SHEET_LIST_SUCCESS'),
  GET_CHECKING_SHEET_LIST_FAILURE: Symbol('GET_CHECKING_SHEET_LIST_FAILURE'),
  GET_FINISHED_SHEET_LIST_SUCCESS: Symbol('GET_FINISHED_SHEET_LIST_SUCCESS'),
  GET_FINISHED_SHEET_LIST_FAILURE: Symbol('GET_FINISHED_SHEET_LIST_FAILURE'),
  GET_WORKER_DEFAULT_SHEET_LIST_SUCCESS: Symbol('GET_WORKER_DEFAULT_SHEET_LIST_SUCCESS'),
  GET_WORKER_DEFAULT_SHEET_LIST_FAILURE: Symbol('GET_WORKER_DEFAULT_SHEET_LIST_FAILURE'),
  GET_WORKER_TIME_FILTER_SHEET_LIST_SUCCESS: Symbol('GET_WORKER_TIME_FILTER_SHEET_LIST_SUCCESS'),
  GET_WORKER_TIME_FILTER_SHEET_LIST_FAILURE: Symbol('GET_WORKER_TIME_FILTER_SHEET_LIST_FAILURE'),
  CHANGE_LOGIN_STATUS: Symbol('CHANGE_LOGIN_STATUS'),
  CHANGE_ROLE_TYPE: Symbol('CHANGE_ROLE_TYPE'),
}


//登录成功
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');

//获取质检派工单成功
export const GET_QUALITYINSPECTOR_SHEET_LIST_SUCCESS = Symbol('GET_QUALITYINSPECTOR_SHEET_LIST_SUCCESS');

//获取质检单-筛选条件-成功
export const GET_QUALITYINSPECTOR_FILTER_SHEET_LIST_SUCCESS = Symbol('GET_QUALITYINSPECTOR_FILTER_SHEET_LIST_SUCCESS');

//获取工艺工序列表成功
export const GET_TECHNOLOGYPROCESS_SHEET_LIST_SUCCESS = Symbol('GET_TECHNOLOGYPROCESS_SHEET_LIST_SUCCESS');

//获取零件号信息成功
export const GET_MECHANICAL_MESSAGE_LIST_SUCCESS = Symbol("GET_MECHANICAL_MESSAGE_LIST_SUCCESS");

export default actionTypes;








