export default {
    THEME_CHANGE: Symbol('THEME_CHANGE'),
    THEME_INIT: Symbol('THEME_INIT'),
    POPULAR_REFRESH: Symbol('POPULAR_REFRESH'),
    POPULAR_lOAD_FAIL:Symbol('POPULAR_lOAD_FAIL'),
    POPULAR_lOAD_SUCCESS:Symbol('POPULAR_lOAD_SUCCESS'),
    POPULAR_LOAD_MORE_SUCCESS: Symbol('POPULAR_LOAD_MORE_SUCCESS'),
    POPULAR_LOAD_MORE_FAIL: Symbol('POPULAR_LOAD_MORE_FAIL'),
    FLUSH_POPULAR_FAVORITE: Symbol('FLUSH_POPULAR_FAVORITE'),
    TRENDING_FLUSH_FAVORITE:  Symbol('TRENDING_FLUSH_FAVORITE'),
    TRENDING_REFRESH:  Symbol('TRENDING_REFRESH'),
    TRENDING_REFRESH_FAIL:  Symbol('TRENDING_REFRESH_FAIL'),
    TRENDING_REFRESH_SUCCESS:  Symbol('TRENDING_REFRESH_SUCCESS'),
    TRENDING_LOAD_MORE_SUCCESS:  Symbol('TRENDING_LOAD_MORE_SUCCESS'),
    TRENDING_LOAD_MORE_FAIL:  Symbol('TRENDING_LOAD_MORE_FAIL'),
    FAVORITE_lOAD_SUCCESS:Symbol('FAVORITE_lOAD_SUCCESS'),
    
};