const actionTypes =  {
  LOGIN_STATUS: Symbol('LOGIN_STATUS'),//登录状态
  AUTHENTICTION_ROLE_SUCCESS:Symbol('AUTHENTICTION_ROLE_SUCCESS'),//认证角色成功
  GET_DEFAULT_SHEET_LIST_SUCCESS: Symbol('GET_DEFAULT_SHEET_LIST_SUCCESS'),//获取默认数据成功
  GET_DEFAULT_SHEET_LIST_FAILURE: Symbol('GET_DEFAULT_SHEET_LIST_FAILURE'),//获取默认派工单失败
  GET_LAST_DAYS_SHEET_LIST_SUCCESS: Symbol('GET_LAST_DAYS_SHEET_LIST_SUCCESS'),//获取车间主任最近三天派工单
  GET_LAST_DAYS_SHEET_LIST_FAILURE: Symbol('GET_LAST_DAYS_SHEET_LIST_FAILURE'),//获取车间主任最近一周派工单
  GET_LAST_WEEK_SHEET_LIST_SUCCESS: Symbol('GET_LAST_WEEK_SHEET_LIST_SUCCESS'),//获取车间主任最近一周派工单
  GET_LAST_WEEK_SHEET_LIST_FAILURE: Symbol('GET_LAST_WEEK_SHEET_LIST_FAILURE'),//获取车间主任最近三天派工单失败
  GET_HALF_YEAR_SHEET_LIST_SUCCESS: Symbol('GET_HALF_YEAR_SHEET_LIST_SUCCESS'),//
  GET_HALF_YEAR_SHEET_LIST_FAILURE: Symbol('GET_HALF_YEAR_SHEET_LIST_FAILURE'),
  GET_UNREPORTED_SHEET_LIST_SUCCESS: Symbol('GET_UNREPORTED_SHEET_LIST_SUCCESS'),//获取车间主任未报工状态派工单
  GET_UNREPORTED_SHEET_LIST_FAILURE: Symbol('GET_UNREPORTED_SHEET_LIST_FAILURE'),
  GET_CHECKING_SHEET_LIST_SUCCESS: Symbol('GET_CHECKING_SHEET_LIST_SUCCESS'),//获取车间主任报工中状态派工单
  GET_CHECKING_SHEET_LIST_FAILURE: Symbol('GET_CHECKING_SHEET_LIST_FAILURE'),
  GET_FINISHED_SHEET_LIST_SUCCESS: Symbol('GET_FINISHED_SHEET_LIST_SUCCESS'),//获取车间主任已完成状态派工单
  GET_FINISHED_SHEET_LIST_FAILURE: Symbol('GET_FINISHED_SHEET_LIST_FAILURE'),
  GET_WORKER_DEFAULT_SHEET_LIST_SUCCESS: Symbol('GET_WORKER_DEFAULT_SHEET_LIST_SUCCESS'),
  GET_WORKER_DEFAULT_SHEET_LIST_FAILURE: Symbol('GET_WORKER_DEFAULT_SHEET_LIST_FAILURE'),
  GET_WORKER_FILTER_SHEET_LIST_SUCCESS: Symbol('GET_WORKER_FILTER_SHEET_LIST_SUCCESS'),
  GET_WORKER_TIME_FILTER_SHEET_LIST_FAILURE: Symbol('GET_WORKER_TIME_FILTER_SHEET_LIST_FAILURE'),
  CHANGE_LOGIN_STATUS: Symbol('CHANGE_LOGIN_STATUS'),//更改登录状态
  CHANGE_ROLE_TYPE: Symbol('CHANGE_ROLE_TYPE'),//更改角色类型
  GET_WORKER_TECHNOLOGY_PROCESS_LISST_SUCCESS:Symbol('GET_WORKER_TECHNOLOGY_PROCESS_LISST_SUCCESS'),//获取派工单工艺工序信息成功
  GET_WORKER_TECHNOLOGTY_PROCESS_LIST_FAILURE:Symbol('GET_WORKER_TECHNOLOGTY_PROCESS_LIST_FAILURE'),//获取派工单工艺工序列表失败
  POST_WORKER_JOB_BOOKING_SUCCESS:Symbol('POST_WORKER_JOB_BOOKING_SUCCESS'),//工人提交报工单成功
  GET_ADDRESS_LIST_SUCCESS:Symbol('GET_ADDRESS_LIST_SUCCESS'),//获取工人通讯录成功
  GET_ADDRESS_LIST_FAILURE:Symbol('GET_ADDRESS_LIST_FAILURE'),//获取工人通讯录失败
  GET_SEARCH_ADDRESS_LIST_SUCCESS:Symbol('GET_SEARCH_ADDRESS_LIST_SUCCESS'),//获取查询字段通讯录成功
  GET_SEARCH_ADDRESS_LIST_FAILURE:Symbol('GET_SEARCH_ADDRESS_LIST_FAILURE'),//获取查询字段通讯录失败
  GET_SEARCH_WORKER_SHEET_LIST_SUCCESS:Symbol('GET_SEARCH_WORKER_SHEET_LIST_SUCCESS'),//获取查询工人派工单成功
  GET_SEARCH_WORKER_SHEET_LIST_FAILURE:Symbol('GET_SEARCH_WORKER_SHEET_LIST_FAILURE'),//获取查询工人派工单成功
  GET_DIRECTOR_DEFAULT_REFRESH_DATA:Symbol('GET_DIRECTOR_DEFAULT_REFRESH_DATA'),//获取车间主任默认更新数据状态
  GET_DIRECTOR_DEFAULT_LOADING_MORE_DATA:Symbol('GET_DIRECTOR_DEFAULT_LOADING_MORE_DATA'),//获取车间主任默认加载更多数据
  WORKER_SHEET_LIST_REFRESH:Symbol('WORKER_SHEET_LIST_REFRESH'),//工人派工单刷新状态
  WORKER_SHEET_LIST_DATA_FAILURE:Symbol('WORKER_SHEET_LIST_DATA_FAILURE'),//获取工人派工单数据失败
  RESET_ALL_SHEET_LIST_DATA: Symbol('RESET_ALL_SHEET_LIST_DATA'),//NoMechanicalList
  GET_NO_MECHANICAL_LIST_SUCCESS:Symbol('GET_NO_MECHANICAL_LIST_SUCCESS'),//获取无零件号质检信息成功
  GET_NO_MECHANICAL_LIST_FAILURE:Symbol('GET_NO_MECHANICAL_LIST_FAILURE'),//获取无零件号质检信息失败
  GET_QUALITYINSPECTOR_SHEET_LIST_SUCCESS:Symbol('GET_QUALITYINSPECTOR_SHEET_LIST_SUCCESS'),//获取质检派工单成功
  GET_QUALITYINSPECTOR_FILTER_SHEET_LIST_SUCCESS:Symbol('GET_QUALITYINSPECTOR_FILTER_SHEET_LIST_SUCCESS'),//获取质检单-筛选条件-成功
  GET_TECHNOLOGYPROCESS_SHEET_LIST_SUCCESS:Symbol('GET_TECHNOLOGYPROCESS_SHEET_LIST_SUCCESS'),//获取工艺工序列表成功
  GET_MECHANICAL_MESSAGE_LIST_SUCCESS:Symbol('GET_MECHANICAL_MESSAGE_LIST_SUCCESS'),//获取零件号信息成功
  RESET_WORKER_ALL_SHEET_LIST_DATA:Symbol('RESET_WORKER_ALL_SHEET_LIST_DATA'),//重置工人派工单得数据
  RESET_SEARCH_SHEET_LIST_DATA:Symbol('RESET_SEARCH_SHEET_LIST_DATA'),//重置根据工人名字查询派工单
  GET_TECHNOLOGY_PROCESS_LIST_REFRESH_STATUS:Symbol('GET_TECHNOLOGY_PROCESS_LIST_REFRESH_STATUS'),//工艺工序初始刷新数据状态
  RESET_WORKER_DEFAULT_SHEET_LIST:Symbol('RESET_WORKER_DEFAULT_SHEET_LIST'),//重置工人派工单默认数据
  LOADING_MORE_DATA:Symbol('LOADING_MORE_DATA'),//加载更多
  DIRECTOR_SHEET_LIST_LOADING_MORE:Symbol('DIRECTOR_SHEET_LIST_LOADING_MORE'),//车间主任加载更多
  REFRESH_WORKER_CELL_SHEET_LIST_DATA:Symbol('REFRESH_WORKER_CELL_SHEET_LIST_DATA'),//刷新工人单个派工单列表数据
  IS_FINISH_OF_WORKER_SHEET_CELL:Symbol('IS_FINISH_OF_WORKER_SHEET_CELL'),//判断派工单是否是完成状态并刷新派工单Cell
  IS_FINISH_OF_FILTER_WORKER_SHEET_CELL:Symbol('IS_FINISH_OF_FILTER_WORKER_SHEET_CELL'),//判断派工单是否是完成状态并刷新筛选派工单
  IS_SUCCESS_OF_FILE_UPLOAD:Symbol('IS_SUCCESS_OF_FILE_UPLOAD'),//判断上传文件是否成功
  GET_QUALITY_INSPECTOR_SHEET_LIST_SUCCESS:Symbol('GET_QUALITY_INSPECTOR_SHEET_LIST_SUCCESS'),//获取无零件号的标准项详情
  ON_CHANGE_NO_CHANICAL_REALVALUE_RESULT_SUCCESS:Symbol('ON_CHANGE_NO_CHANICAL_REALVALUE_RESULT_SUCCESS'),//改变无零件号标准项的质检结果值
  GET_STANDAR_ITEM_SUCCESS:Symbol('GET_STANDAR_ITEM_SUCCESS'),//获取标准项成功
  QUALIYT_INSPECTOR_SHEET_LIST_DATA_FAILURE:Symbol('QUALIYT_INSPECTOR_SHEET_LIST_DATA_FAILURE'),//获取质检派工单数据失败
  GET_QUALITY_INSPECTOR_TECHNOLOGTY_PROCESS_LIST_FAILURE:Symbol('GET_QUALITY_INSPECTOR_TECHNOLOGTY_PROCESS_LIST_FAILURE'),//获取质检单工艺工序列表失败
  GET_STANDAR_ITEM_FAILURE:Symbol('GET_STANDAR_ITEM_FAILURE'),//获取有零件号标准项失败
  ON_CHANGE_STANDARD_ITEM_LIST_SUCCESS:Symbol('ON_CHANGE_STANDARD_ITEM_LIST_SUCCESS'),//改变有零件号标准项的质检结果值
  GET_NO_MECHANICAL_STANDAR_ITEM_FAILURE:Symbol("GET_NO_MECHANICAL_STANDAR_ITEM_FAILURE"),//获取无零件号的标准项失败
  QUALITY_SHEET_LIST_REFRESH:Symbol("QUALITY_SHEET_LIST_REFRESH"),//获取默认质检单
  RESET_QualityINSPECTOR_DEFAULT_SHEET_LIST:Symbol('RESET_QualityINSPECTOR_DEFAULT_SHEET_LIST'),//重置质检单默认数据
  GET_SCRAP_PROCESS_LIST_SUCESS:Symbol('GET_SCRAP_PROCESS_LIST_SUCESS'),//获取报废工艺
  GET_FACTORY__LIST_SUCESS:Symbol('GET_FACTORY__LIST_SUCESS'),//获取工厂列表
  GET_SUPPLIER__LIST_SUCESS:Symbol('GET_SUPPLIER__LIST_SUCESS'),//获取供应商列表
  GET_MONITOR__LIST_SUCESS:Symbol('GET_MONITOR__LIST_SUCESS'),//获取班组列表成功
}

export default actionTypes;








